Controllers/BillPayController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Assignment_2.Data;
using Assignment_2.Models;

namespace Assignment_2.Controllers
{
    public class BillPayController : Controller
    {
        private int CustomerID => HttpContext.Session.GetInt32(nameof(Customer.CustomerID)).Value; 
        private readonly MCBAContext _context;

        public BillPayController(MCBAContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Customers.FindAsync(CustomerID));
        }

        public IActionResult CreateBill() => View();
       
        [HttpPost]
        public async Task<IActionResult> CreateBill(int id, BillPay billPay)
        {
            var account = await _context.Accounts.FindAsync(id);
            var payee = await _context.Payees.FindAsync(billPay.PayeeID);

            if (payee == null)
            {
                ModelState.AddModelError(nameof(billPay.PayeeID), "The payee ID does not exist.");
                ViewBag.Amount = billPay.Amount;
                return View(billPay);
            }

            if (ModelState.IsValid)
            {
                billPay.AccountNumber = id;
                billPay.ScheduleTimeUtc = billPay.ScheduleTimeUtc.ToUniversalTime();
                account.BillPay(billPay);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(billPay);
        }

        public async Task<IActionResult> ViewBill(int id) => View(await _context.Accounts.FindAsync(id));

        public async Task<IActionResult> EditBill(int id)
        {
            var billPay = await _context.BillPays.FindAsync(id);
            return View(billPay);
        }

        [HttpPost]
        public async Task<IActionResult> EditBill(int id, BillPay billPay)
        {
            var account = await _context.Accounts.FindAsync(billPay.AccountNumber);
            var payee = await _context.Payees.FindAsync(billPay.PayeeID);

            if (payee == null)
            {
                ModelState.AddModelError(nameof(billPay.PayeeID), "The payee ID does not exist.");
                ViewBag.Amount = billPay.Amount;
                return View(billPay);
            }

            if (ModelState.IsValid)
            {
                var bill = await _context.BillPays.FindAsync(id);
                billPay.ScheduleTimeUtc = billPay.ScheduleTimeUtc.ToUniversalTime();
                bill.Update(billPay);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(billPay);
        }

        public async Task<IActionResult> DeleteBill(int id)
        {
            var billPay = await _context.BillPays.FindAsync(id);
            _context.BillPays.Remove(billPay);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/LoginController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Assignment_2.Data;
using Assignment_2.Models;
using Microsoft.AspNetCore.Http;
using SimpleHashing;

namespace Assignment_2.Controllers
{
    public class LoginController : Controller
    {
        private readonly MCBAContext _context;

        public LoginController(MCBAContext context)
        {
            _context = context;
        }

        public IActionResult Index() => View();

        [HttpPost]
        public async Task<IActionResult> Index(string loginID, string password)
        {
            var login = await _context.Logins.FindAsync(loginID);

            if (login.Customer.Locked==true)
            {
                ModelState.AddModelError("LoginFailed", "Login failed, Account is locked by Admin.");
                return View(new Login { LoginID = loginID });
            }

            if (login == null || !PBKDF2.Verify(login.PasswordHash, password))
            {
                ModelState.AddModelError("LoginFailed", "Login failed, please try again.");
                return View(new Login { LoginID = loginID });
            }

            // Login customer.
            HttpContext.Session.SetInt32(nameof(Customer.CustomerID), login.CustomerID);
            HttpContext.Session.SetString(nameof(Login.LoginID), login.LoginID);
            HttpContext.Session.SetString(nameof(Customer.Name), login.Customer.Name); 

            return RedirectToAction("Index", "Customer");
        }

        public IActionResult Logout()
        {
            // Logout customer.
            HttpContext.Session.Clear();

            return RedirectToAction("Index", "Home");
        }
    }
}

Controllers/StatementController.cs
using System.Threading.Tasks;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using Assignment_2.Data;
using Assignment_2.Models;
using X.PagedList;
using System.Collections.Generic;

namespace Assignment_2.Controllers
{
    public class StatementController : Controller
    {
        private int CustomerID => HttpContext.Session.GetInt32(nameof(Customer.CustomerID)).Value;
        private readonly MCBAContext _context;
        private const string AccountSessionKey = "_AccountSessionKey";

        public StatementController(MCBAContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var customer = await _context.Customers.FindAsync(CustomerID);
            return View(customer);
        }

        
        public async Task<IActionResult> AccountStatement(int id)
        {
            {
                var account = await _context.Accounts.FindAsync(id);
                var serializerSettings = new JsonSerializerSettings { PreserveReferencesHandling = PreserveReferencesHandling.Objects };
                string accountJson = JsonConvert.SerializeObject(account, Formatting.Indented, serializerSettings);
                HttpContext.Session.SetString(AccountSessionKey, accountJson);
                return RedirectToAction(nameof(Statement));
            }
        }

        public async Task<IActionResult> Statement(int? page = 1)
        {
            var accountJson = HttpContext.Session.GetString(AccountSessionKey);

            if (accountJson == null)
                return RedirectToAction(nameof(Index));

            var account = JsonConvert.DeserializeObject<Account>(accountJson);
            ViewBag.Account = account;

            const int pageSize = 4;

            var pagedList = await _context.Transactions.Where(x => x.AccountNumber == account.AccountNumber).
                OrderByDescending(x => x.TransactionTimeUtc).ToPagedListAsync(page, pageSize);
            return View(pagedList);
        }

        public async Task<IActionResult> Graph(int id)
        {
            {
                var transactions = await _context.Transactions.Where(x => x.AccountNumber == id).ToListAsync<Transaction>();

                calcMoneyInOut(transactions);
                calcTransactionTypePercentage(transactions);

                return View();
            }
        }

        public void calcMoneyInOut(List<Transaction> transactions)
        {
            decimal moneyIn = 0;
            decimal moneyOut = 0;

            foreach (var transaction in transactions)
            {
                if (transaction.TransactionType == TransactionType.Deposit)
                {
                    moneyIn += transaction.Amount;
                }
                else if (transaction.TransactionType == TransactionType.Withdraw || transaction.TransactionType == TransactionType.BillPay
                    || transaction.TransactionType == TransactionType.ServiceCharge)
                {
                    moneyOut += transaction.Amount;
                }
                else if (transaction.TransactionType == TransactionType.Transfer && transaction.DestinationAccount == null)
                {
                    moneyIn += transaction.Amount;
                }
                else
                    moneyOut += transaction.Amount;
            }

            ViewBag.In = moneyIn;
            ViewBag.Out = moneyOut;
        }

        public void calcTransactionTypePercentage(List<Transaction> transactions)
        {
            decimal service = 0;
            decimal deposit = 0;
            decimal withdraw = 0;
            decimal transferIn = 0;
            decimal transferOut = 0;
            decimal billpay = 0;
            decimal total = 0;

            foreach (var transaction in transactions)
            {
                if (transaction.TransactionType == TransactionType.Deposit)
                {
                    deposit += transaction.Amount;
                }
                else if (transaction.TransactionType == TransactionType.Withdraw)
                {
                    withdraw += transaction.Amount;
                }
                else if (transaction.TransactionType == TransactionType.ServiceCharge)
                {
                    service += transaction.Amount;
                }
                else if (transaction.TransactionType == TransactionType.BillPay)
                {
                    billpay += transaction.Amount;
                }
                else if (transaction.TransactionType == TransactionType.Transfer && transaction.DestinationAccount == null)
                {
                    transferIn += transaction.Amount;
                }
                else
                    transferOut += transaction.Amount;
            }

            total = deposit + withdraw + service + billpay + transferIn + transferOut;

            ViewBag.Deposit = deposit / total;
            ViewBag.Withdraw = withdraw / total;
            ViewBag.Service = service / total;
            ViewBag.BillPay = billpay / total;
            ViewBag.TransferIn = transferIn / total;
            ViewBag.TransferOut = transferOut / total;
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MCBA</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav">
                        @{
                            var isLoggedIn = Context.Session.GetInt32(nameof(Customer.CustomerID)).HasValue;
                        }
                        @if (isLoggedIn)
                        {
                            <li class="nav-item">
                                <span class="nav-link text-dark">
                                    Welcome, @Context.Session.GetString(nameof(Customer.Name))
                                </span>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Login" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Login" asp-action="index">Login</a>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav flex-grow-1">
                        @if (isLoggedIn)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Customer" asp-action="Index">Account</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="BillPay" asp-action="Index">Bill Pay</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Statement" asp-action="Index">Statement</a>
                            </li>
                            <li class="nav-item">
                                <div class="btn-group">
                                    <a class="nav-link text-dark dropdown-toggle" data-toggle="dropdown">User Profile</a>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item" asp-controller="Customer" asp-action="UpdateProfile">Update Profile</a>
                                        <a class="dropdown-item" asp-controller="Customer" asp-action="ChangePassword">Change Password</a>
                                    </div>
                                </div>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container"> &copy;  WDT2021 - A2 - S3333925 </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>